// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPyQAapbGECQiHLJCf_o6g6k1czkkhR2A',
    appId: '1:245882355678:web:08be91b0963275fe8e274f',
    messagingSenderId: '245882355678',
    projectId: 'noya-51691',
    authDomain: 'noya-51691.firebaseapp.com',
    storageBucket: 'noya-51691.firebasestorage.app',
    measurementId: 'G-SM2506Z4EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS-eZDKexFhVqRvh8w4KMinHqqWQUoa7Y',
    appId: '1:245882355678:android:e95b6fa9b44226088e274f',
    messagingSenderId: '245882355678',
    projectId: 'noya-51691',
    storageBucket: 'noya-51691.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8qKInkz0-fCpEsN2S0GuNiGP-NqcUTk',
    appId: '1:245882355678:ios:e62afd2c63ee3c428e274f',
    messagingSenderId: '245882355678',
    projectId: 'noya-51691',
    storageBucket: 'noya-51691.firebasestorage.app',
    iosBundleId: 'com.kareem.noyaapp.noyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPyQAapbGECQiHLJCf_o6g6k1czkkhR2A',
    appId: '1:245882355678:web:b9936cb365ffab548e274f',
    messagingSenderId: '245882355678',
    projectId: 'noya-51691',
    authDomain: 'noya-51691.firebaseapp.com',
    storageBucket: 'noya-51691.firebasestorage.app',
    measurementId: 'G-6NY6G7T5LV',
  );
}
